### ISSUE TITLE
[Bug][Azure Devops] 0.18.0 Regression: Unable to list repositories 

### ISSUE THREAD

**Issue by oliverisaac** [apache/devlake#5855]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I try to add an azure devops data source (repo) there is this (redacted) error log:

```
time="2023-08-10 21:54:06" level=info msg="DEBUG: Starting new HTTPS connection (1): dev.azure.com:443"
time="2023-08-10 21:54:06" level=info msg="DEBUG: https://dev.azure.com:443 "GET /myorg/devlake/_apis/git/repositories?api-version=7.0 HTTP/1.1" 200 None"
time="2023-08-10 21:54:06" level=info msg="DEBUG: https://dev.azure.com:443 "GET /myorg/devlake/_apis/serviceendpoint/endpoints?api-version=7.0 HTTP/1.1" 200 1494"
time="2023-08-10 21:54:06" level=info msg="DEBUG: https://dev.azure.com:443 "GET /myorg/devlake/_apis/sourceProviders/SnykAuth/repositories?serviceEndpointId=12341234-1234-1234-1223-123412341234&api-version=7.0 HTTP/1.1" 400 306"
time="2023-08-10 21:54:06" level=error msg="Traceback (most recent call last):"
time="2023-08-10 21:54:06" level=error msg="  File "/app/python/plugins/azuredevops/azuredevops/main.py", line 150, in <module>"
time="2023-08-10 21:54:06" level=error msg="    AzureDevOpsPlugin.start()"
time="2023-08-10 21:54:06" level=error msg="  File "/app/python/pydevlake/pydevlake/plugin.py", line 256, in start"
time="2023-08-10 21:54:06" level=error msg="    fire.Fire(PluginCommands(plugin))"
time="2023-08-10 21:54:06" level=error msg="  File "/app/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", line 141, in Fire"
time="2023-08-10 21:54:06" level=error msg="    component_trace = _Fire(component, args, parsed_flag_args, context, name)"
time="2023-08-10 21:54:06" level=error msg="  File "/app/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire"
time="2023-08-10 21:54:06" level=error msg="    component, remaining_args = _CallAndUpdateTrace("
time="2023-08-10 21:54:06" level=error msg="  File "/app/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace"
time="2023-08-10 21:54:06" level=error msg="    component = fn(*varargs, **kwargs)"
time="2023-08-10 21:54:06" level=error msg="  File "/app/python/pydevlake/pydevlake/ipc.py", line 54, in wrapper"
time="2023-08-10 21:54:06" level=error msg="    ret = func(self, *args)"
time="2023-08-10 21:54:06" level=error msg="  File "/app/python/pydevlake/pydevlake/ipc.py", line 109, in remote_scopes"
time="2023-08-10 21:54:06" level=error msg="    return self._plugin.make_remote_scopes(c, group_id)"
time="2023-08-10 21:54:06" level=error msg="  File "/app/python/pydevlake/pydevlake/plugin.py", line 117, in make_remote_scopes"
time="2023-08-10 21:54:06" level=error msg="    for tool_scope in self.remote_scopes(connection, group_id):"
time="2023-08-10 21:54:06" level=error msg="  File "/app/python/plugins/azuredevops/azuredevops/main.py", line 97, in remote_scopes"
time="2023-08-10 21:54:06" level=error msg="    res = api.external_repositories(org, proj, provider, endpoint['id'])"
time="2023-08-10 21:54:06" level=error msg="  File "/app/python/plugins/azuredevops/azuredevops/api.py", line 90, in external_repositories"
time="2023-08-10 21:54:06" level=error msg="    return self.get(org, project, '_apis/sourceProviders', provider, 'repositories', serviceEndpointId=endpoint_id)"
time="2023-08-10 21:54:06" level=error msg="  File "/app/python/pydevlake/pydevlake/api.py", line 145, in get"
time="2023-08-10 21:54:06" level=error msg="    return self.send(req)"
time="2023-08-10 21:54:06" level=error msg="  File "/app/python/pydevlake/pydevlake/api.py", line 127, in send"
time="2023-08-10 21:54:06" level=error msg="    response = self._apply_hooks(response, self.response_hooks())"
time="2023-08-10 21:54:06" level=error msg="  File "/app/python/pydevlake/pydevlake/api.py", line 133, in _apply_hooks"
time="2023-08-10 21:54:06" level=error msg="    result = hook.apply(target, self)"
time="2023-08-10 21:54:06" level=error msg="  File "/app/python/pydevlake/pydevlake/api.py", line 191, in apply"
time="2023-08-10 21:54:06" level=error msg="    return self.fn(api, response)"
time="2023-08-10 21:54:06" level=error msg="  File "/app/python/pydevlake/pydevlake/api.py", line 330, in handle_error"
time="2023-08-10 21:54:06" level=error msg="    raise APIException(response)"
time="2023-08-10 21:54:06" level=error msg="pydevlake.api.APIException: APIException: https://dev.azure.com/myorg/devlake/_apis/sourceProviders/SnykAuth/repositories?serviceEndpointId=12341234-1234-abcd-abcd-123412341234&api-version=7.0: 400 body: b'{"$id":"1","innerException":null,"message":"The repository type SnykAuth is not supported.","typeName":"Microsoft.TeamFoundation.Build.WebApi.BuildRepositoryTypeNotSupportedException, Microsoft.TeamFoundation.Build2.WebApi","typeKey":"BuildRepositoryTypeNotSupportedException","errorCode":0,"eventId":3000}'"
time="2023-08-10 21:54:06" level=error msg="HTTP 500 error
	caused by: get error when invoking remote function remote-scopes
	Wraps: (2) remote error response:
	  | Traceback (most recent call last):
	  |   File "/app/python/plugins/azuredevops/azuredevops/main.py", line 150, in <module>
	  |     AzureDevOpsPlugin.start()
	  |   File "/app/python/pydevlake/pydevlake/plugin.py", line 256, in start
	  |     fire.Fire(PluginCommands(plugin))
	  |   File "/app/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
	  |     component_trace = _Fire(component, args, parsed_flag_args, context, name)
	  |   File "/app/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
	  |     component, remaining_args = _CallAndUpdateTrace(
	  |   File "/app/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
	  |     component = fn(*varargs, **kwargs)
	  |   File "/app/python/pydevlake/pydevlake/ipc.py", line 54, in wrapper
	  |     ret = func(self, *args)
	  |   File "/app/python/pydevlake/pydevlake/ipc.py", line 109, in remote_scopes
	  |     return self._plugin.make_remote_scopes(c, group_id)
	  |   File "/app/python/pydevlake/pydevlake/plugin.py", line 117, in make_remote_scopes
	  |     for tool_scope in self.remote_scopes(connection, group_id):
	  |   File "/app/python/plugins/azuredevops/azuredevops/main.py", line 97, in remote_scopes
	  |     res = api.external_repositories(org, proj, provider, endpoint['id'])
	  |   File "/app/python/plugins/azuredevops/azuredevops/api.py", line 90, in external_repositories
	  |     return self.get(org, project, '_apis/sourceProviders', provider, 'repositories', serviceEndpointId=endpoint_id)
	  |   File "/app/python/pydevlake/pydevlake/api.py", line 145, in get
	  |     return self.send(req)
	  |   File "/app/python/pydevlake/pydevlake/api.py", line 127, in send
	  |     response = self._apply_hooks(response, self.response_hooks())
	  |   File "/app/python/pydevlake/pydevlake/api.py", line 133, in _apply_hooks
	  |     result = hook.apply(target, self)
	  |   File "/app/python/pydevlake/pydevlake/api.py", line 191, in apply
	  |     return self.fn(api, response)
	  |   File "/app/python/pydevlake/pydevlake/api.py", line 330, in handle_error
	  |     raise APIException(response)
	  | pydevlake.api.APIException: APIException: https://dev.azure.com/myorg/devlake/_apis/sourceProviders/SnykAuth/repositories?serviceEndpointId=12345678_0000_1234_0000_123412341234&api-version=7.0: 400 body: b'{"$id":"1","innerException":null,"message":"The repository type SnykAuth is not supported.","typeName":"Microsoft.TeamFoundation.Build.WebApi.BuildRepositoryTypeNotSupportedException, Microsoft.TeamFoundation.Build2.WebApi","typeKey":"BuildRepositoryTypeNotSupportedException","errorCode":0,"eventId":3000}'
	Wraps: (3) exit status 1
	Wraps: (4) exit status 1
	Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *exec.ExitError"
```

### What do you expect to happen

Should be able to add a repo. This is confirmed to work in 0.17.0

### How to reproduce

Use devlake 0.18.0-beta4 and try to add an azdo repo. It might have to do with the fact we have snyk set up. 

### Version

0.18.0-beta4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Hi, @CamilleTeruel, seems like the API reported error, weird though since we didn't touch this part of the code, do you have any idea why it is happening?
