### ISSUE TITLE
[Bug][Config UI] Errors when run config-ui

### ISSUE THREAD

**Issue by perhapzz** [apache/devlake#6100]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

As I am following the [Developer Steup](https://devlake.apache.org/docs/DeveloperManuals/DeveloperSetup) steps to setup devlake on my own macbook, it comes out some errors that I can't address. When I run config-ui `make configure-dev`, the information about the error as follow.

```
cd config-ui; yarn; yarn start
/Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:190
`,CHAR_NO_BREAK_SPACE:"\xA0",CHAR_PERCENT:"%",CHAR_PLUS:"+",CHAR_QUESTION_MARK:"?",CHAR_RIGHT_ANGLE_BRACKET:">",CHAR_RIGHT_CURLY_BRACE:"}",CHAR_RIGHT_SQUARE_BRACKET:"]",CHAR_SEMICOLON:";",CHAR_SINGLE_QUOTE:"'",CHAR_SPACE:" ",CHAR_TAB:"        ",CHAR_UNDERSCORE:"_",CHAR_VERTICAL_LINE:"|",CHAR_ZERO_WIDTH_NOBREAK_SPACE:"\uFEFF"}});var XJ=w((_$e,VJ)=>{"use strict";var pwe=xy(),{MAX_LENGTH:JJ,CHAR_BACKSLASH:gx,CHAR_BACKTICK:dwe,CHAR_COMMA:Cwe,CHAR_DOT:mwe,CHAR_LEFT_PARENTHESES:Ewe,CHAR_RIGHT_PARENTHESES:Iwe,CHAR_LEFT_CURLY_BRACE:ywe,CHAR_RIGHT_CURLY_BRACE:wwe,CHAR_LEFT_SQUARE_BRACKET:WJ,CHAR_RIGHT_SQUARE_BRACKET:zJ,CHAR_DOUBLE_QUOTE:Bwe,CHAR_SINGLE_QUOTE:Qwe,CHAR_NO_BREAK_SPACE:bwe,CHAR_ZERO_WIDTH_NOBREAK_SPACE:Swe}=qJ(),vwe=(r,e={})=>{if(typeof r!="string")throw new TypeError("Expected a string");let t=e||{},i=typeof t.maxLength=="number"?Math.min(JJ,t.maxLength):JJ;if(r.length>i)throw new SyntaxError(`Input length (${

TypeError: Cannot destructure property `Resolver` of 'undefined' or 'null'.
    at w (/Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:190:91539)
    at /Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:4:510
    at Yt (/Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:191:21828)
    at /Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:4:510
    at io (/Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:195:21663)
    at /Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:4:510
    at YA (/Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:195:22835)
    at /Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:4:510
    at Is (/Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:195:26074)
    at /Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:4:510
/Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:190
`,CHAR_NO_BREAK_SPACE:"\xA0",CHAR_PERCENT:"%",CHAR_PLUS:"+",CHAR_QUESTION_MARK:"?",CHAR_RIGHT_ANGLE_BRACKET:">",CHAR_RIGHT_CURLY_BRACE:"}",CHAR_RIGHT_SQUARE_BRACKET:"]",CHAR_SEMICOLON:";",CHAR_SINGLE_QUOTE:"'",CHAR_SPACE:" ",CHAR_TAB:"        ",CHAR_UNDERSCORE:"_",CHAR_VERTICAL_LINE:"|",CHAR_ZERO_WIDTH_NOBREAK_SPACE:"\uFEFF"}});var XJ=w((_$e,VJ)=>{"use strict";var pwe=xy(),{MAX_LENGTH:JJ,CHAR_BACKSLASH:gx,CHAR_BACKTICK:dwe,CHAR_COMMA:Cwe,CHAR_DOT:mwe,CHAR_LEFT_PARENTHESES:Ewe,CHAR_RIGHT_PARENTHESES:Iwe,CHAR_LEFT_CURLY_BRACE:ywe,CHAR_RIGHT_CURLY_BRACE:wwe,CHAR_LEFT_SQUARE_BRACKET:WJ,CHAR_RIGHT_SQUARE_BRACKET:zJ,CHAR_DOUBLE_QUOTE:Bwe,CHAR_SINGLE_QUOTE:Qwe,CHAR_NO_BREAK_SPACE:bwe,CHAR_ZERO_WIDTH_NOBREAK_SPACE:Swe}=qJ(),vwe=(r,e={})=>{if(typeof r!="string")throw new TypeError("Expected a string");let t=e||{},i=typeof t.maxLength=="number"?Math.min(JJ,t.maxLength):JJ;if(r.length>i)throw new SyntaxError(`Input length (${

TypeError: Cannot destructure property `Resolver` of 'undefined' or 'null'.
    at w (/Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:190:91539)
    at /Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:4:510
    at Yt (/Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:191:21828)
    at /Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:4:510
    at io (/Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:195:21663)
    at /Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:4:510
    at YA (/Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:195:22835)
    at /Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:4:510
    at Is (/Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:195:26074)
    at /Users/phuazheng/GolandProjects/github/incubator-devlake/config-ui/.yarn/releases/yarn-3.4.1.cjs:4:510
make: *** [configure-dev] Error 1
```

### What do you expect to happen

I hope to run config-ui in dev mode.

### How to reproduce

<img width="280" alt="image" src="https://github.com/apache/incubator-devlake/assets/48175595/f9b46d55-2b9a-4067-abef-37d856ada572">

The processor of my macbook is Intel chip, and my macos is 13.5.2 (22G91)

```
$ yarn -v
1.22.19
```

### Version

v0.19.0-beta2

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@mintsweet Hi, could you take a look at this issue, thanks.

**Comment by mintsweet** [comment]
Hi @perhapzz, you can try the following two ways:

1. Upgrade yarn to 2 or above.
2. Open the terminal under `xxx/config-ui`` and execute `yarn`.
