### ISSUE TITLE
[Bug][Backend] Cannot start the backend service

### ISSUE THREAD

**Issue by d4x1** [apache/devlake#6168]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Run devlake backend with command `make godev`, the compile stage is accomplished, but failed to run server. 

The errors look like:
```
➜  lake git:(main) make godev
make godev -C backend
DISABLED_REMOTE_PLUGINS=true make build-plugin run
if [ "" = "none" ]; then \
		echo "Building plugins will be skipped"; \
	elif [ "" = "true" ]; then \
		PLUGIN= sh scripts/compile-plugins.sh -gcflags='all=-N -l'; \
	else \
		PLUGIN= sh scripts/compile-plugins.sh; \
	fi
Usage: 
  build all plugins:              scripts/compile-plugins.sh [golang build flags...]
  build and keep specified plugins only: PLUGIN=github,jira scripts/compile-plugins.sh [golang build flags...]
Building all plugins
Building plugin ae to bin/plugins/ae/ae.so with args: 
Building plugin bamboo to bin/plugins/bamboo/bamboo.so with args: 
Building plugin bitbucket to bin/plugins/bitbucket/bitbucket.so with args: 
Building plugin circleci to bin/plugins/circleci/circleci.so with args: 
Building plugin customize to bin/plugins/customize/customize.so with args: 
Building plugin dbt to bin/plugins/dbt/dbt.so with args: 
Building plugin dora to bin/plugins/dora/dora.so with args: 
Building plugin feishu to bin/plugins/feishu/feishu.so with args: 
Building plugin gitee to bin/plugins/gitee/gitee.so with args: 
Building plugin gitextractor to bin/plugins/gitextractor/gitextractor.so with args: 
Building plugin github to bin/plugins/github/github.so with args: 
Building plugin github_graphql to bin/plugins/github_graphql/github_graphql.so with args: 
Building plugin gitlab to bin/plugins/gitlab/gitlab.so with args: 
Building plugin icla to bin/plugins/icla/icla.so with args: 
Building plugin jenkins to bin/plugins/jenkins/jenkins.so with args: 
Building plugin jira to bin/plugins/jira/jira.so with args: 
Building plugin org to bin/plugins/org/org.so with args: 
Building plugin pagerduty to bin/plugins/pagerduty/pagerduty.so with args: 
Building plugin refdiff to bin/plugins/refdiff/refdiff.so with args: 
Building plugin slack to bin/plugins/slack/slack.so with args: 
Building plugin sonarqube to bin/plugins/sonarqube/sonarqube.so with args: 
Building plugin starrocks to bin/plugins/starrocks/starrocks.so with args: 
Building plugin tapd to bin/plugins/tapd/tapd.so with args: 
Building plugin teambition to bin/plugins/teambition/teambition.so with args: 
Building plugin trello to bin/plugins/trello/trello.so with args: 
Building plugin webhook to bin/plugins/webhook/webhook.so with args: 
Building plugin zentao to bin/plugins/zentao/zentao.so with args: 
go run server/main.go
Version:  dev
time="2023-09-28 15:34:09" level=info msg="migration initialized"
time="2023-09-28 15:34:09" level=info msg="plugin loaded ae"
time="2023-09-28 15:34:10" level=info msg="plugin loaded bamboo"
time="2023-09-28 15:34:10" level=info msg="plugin loaded bitbucket"
time="2023-09-28 15:34:10" level=info msg="plugin loaded circleci"
time="2023-09-28 15:34:10" level=info msg="plugin loaded customize"
time="2023-09-28 15:34:10" level=info msg="plugin loaded dbt"
time="2023-09-28 15:34:10" level=info msg="plugin loaded dora"
time="2023-09-28 15:34:10" level=info msg="plugin loaded feishu"
time="2023-09-28 15:34:10" level=info msg="plugin loaded gitee"
time="2023-09-28 15:34:10" level=info msg="plugin loaded gitextractor"
time="2023-09-28 15:34:10" level=info msg="\x1b[31;1m/Users/houlinwei/Code/go/src/github.com/merico-dev/lake/backend/impls/dalgorm/dalgorm.go:284 \x1b[35;1mError 1146 (42S02): Table 'lake._tool_github_connections' doesn't exist\n\x1b[0m\x1b[33m[2.005ms] \x1b[34;1m[rows:-]\x1b[0m SELECT * FROM `_tool_github_connections` LIMIT 1"
panic: Error 1146 (42S02): Table 'lake._tool_github_connections' doesn't exist (500)
Wraps: (2) Error 1146 (42S02): Table 'lake._tool_github_connections' doesn't exist
Error types: (1) *hintdetail.withDetail (2) *mysql.MySQLError

goroutine 1 [running]:
github.com/apache/incubator-devlake/core/errors.Must1[...](...)
	/Users/houlinwei/Code/go/src/github.com/merico-dev/lake/backend/core/errors/util.go:40
github.com/apache/incubator-devlake/helpers/srvhelper.NewModelSrvHelper[...]({0x105e2cc38, 0x14000146b70})
	/Users/houlinwei/Code/go/src/github.com/merico-dev/lake/backend/helpers/srvhelper/model_service_helper.go:56 +0x3a8
github.com/apache/incubator-devlake/helpers/srvhelper.NewConnectionSrvHelper[...](...)
	/Users/houlinwei/Code/go/src/github.com/merico-dev/lake/backend/helpers/srvhelper/connection_service_helper.go:44
github.com/apache/incubator-devlake/helpers/pluginhelper/api.NewDataSourceHelpers[...]({0x105e2cc38, 0x14000146b70}, {0x165c41c74, 0x6}, {0x14000318bb0, 0x1, 0x1})
	/Users/houlinwei/Code/go/src/github.com/merico-dev/lake/backend/helpers/pluginhelper/api/ds_helper.go:42 +0x4c
github.com/apache/incubator-devlake/plugins/github/api.Init({0x105e2cc38?, 0x14000146b70}, {0x1660972b8, 0x10715e680})
	/Users/houlinwei/Code/go/src/github.com/merico-dev/lake/backend/plugins/github/api/init.go:47 +0xdc
github.com/apache/incubator-devlake/plugins/github/impl.Github.Init(...)
	/Users/houlinwei/Code/go/src/github.com/merico-dev/lake/backend/plugins/github/impl/impl.go:75
github.com/apache/incubator-devlake/core/runner.LoadGoPlugins.func1({0x140005916e0, 0x1c}, {0x105e286e8, 0x1400004f2c0}, {0x0?, 0x0?})
	/Users/houlinwei/Code/go/src/github.com/merico-dev/lake/backend/core/runner/loader.go:72 +0x224
path/filepath.walkDir({0x140005916e0, 0x1c}, {0x105e286e8, 0x1400004f2c0}, 0x14001987c10)
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/path/filepath/path.go:457 +0x44
path/filepath.walkDir({0x14000479cc8, 0x12}, {0x105e286e8, 0x1400004ea00}, 0x14001987c10)
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/path/filepath/path.go:479 +0x224
path/filepath.walkDir({0x140002f7d10, 0xb}, {0x105e28720, 0x140005019d0}, 0x14001987c10)
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/path/filepath/path.go:479 +0x224
path/filepath.WalkDir({0x140002f7d10, 0xb}, 0x14000347c10)
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/path/filepath/path.go:547 +0xb0
github.com/apache/incubator-devlake/core/runner.LoadGoPlugins({0x105e2cc38, 0x14000146b70})
	/Users/houlinwei/Code/go/src/github.com/merico-dev/lake/backend/core/runner/loader.go:52 +0x64
github.com/apache/incubator-devlake/core/runner.LoadPlugins({0x105e2cc38, 0x14000146b70})
	/Users/houlinwei/Code/go/src/github.com/merico-dev/lake/backend/core/runner/loader.go:37 +0x24
github.com/apache/incubator-devlake/server/services.Init()
	/Users/houlinwei/Code/go/src/github.com/merico-dev/lake/backend/server/services/init.go:87 +0x38
github.com/apache/incubator-devlake/server/api.CreateApiService()
	/Users/houlinwei/Code/go/src/github.com/merico-dev/lake/backend/server/api/api.go:63 +0x30
main.main()
	/Users/houlinwei/Code/go/src/github.com/merico-dev/lake/backend/server/main.go:33 +0x38
exit status 2
make[2]: *** [run] Error 1
make[1]: *** [godev] Error 2
make: *** [godev] Error 2

```

### What do you expect to happen

Run server sucessfully.

### How to reproduce

fetch the latest main branch, and run `make godev`.

### Anything else

I have deleted all tables in devlake's database, and not sure it matters of not.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
Did you delete (or truncate) the migrations history table too? If not, the server code is going to think all migrations are up to date and not rerun any of them. Based on the logs above it seems migrations didn't run which leads me to assume this.

**Comment by d4x1** [comment]
> Did you delete (or truncate) the migrations history table too? If not, the server code is going to think all migrations are up to date and not rerun any of them. Based on the logs above it seems migrations didn't run which leads me to assume this.

Yes. I droped all  tables in the database.
